### ISSUE TITLE
Develop "Raston Group" website

### ISSUE THREAD

**Issue by spectroscopy** [RastonLab/Other#1]
Heres the content: 
[Raston Group website v0a.docx](https://github.com/RastonLab/Other/files/8754475/Raston.Group.website.v0a.docx)

**Comment by hcientist** [comment]
http://hcientist.com
https://www.jasonforsyth.net/

**Comment by hcientist** [comment]
Image of white light divided into spectrum (rainbow 😍 🌈) can make the website, inviting, with appropriate imagery
